package com.fintrack.expense.dto;

import lombok.Builder;
import lombok.Getter;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;

/**
 * Response DTO for a single expense record.
 *
 * Matches the TRD example contract exactly:
 * {
 *   "id": 88,
 *   "amount": 250.00,
 *   "category": { "id": 4, "name": "Food", "color": "#F8C8DC", "icon": "utensils" },
 *   "description": "Groceries",
 *   "expenseDate": "2026-06-18",
 *   "paymentMethod": "UPI",
 *   "createdAt": "2026-06-18T09:12:00Z"
 * }
 *
 * CategorySummary is a flat, minimal nested object — only what the frontend needs
 * to render the category badge (name + color) and icon.
 * We don't embed the full CategoryResponse to keep the payload lean.
 *
 * WHY NOT include userId in the response?
 * The client is always authenticated — they know who they are.
 * Echoing userId back is unnecessary data and a minor info-leak.
 */
@Getter
@Builder
public class ExpenseResponse {

    private Long id;
    private BigDecimal amount;
    private CategorySummary category;
    private String description;
    private LocalDate expenseDate;
    private String paymentMethod;
    private Instant createdAt;

    /**
     * Minimal category info embedded in the expense response.
     * Generated by ExpenseMapper from the nested Category entity.
     */
    @Getter
    @Builder
    public static class CategorySummary {
        private Long id;
        private String name;
        private String color;
        private String icon;
    }
}
