package com.fintrack.category.dto;

import com.fintrack.category.CategoryType;
import lombok.Builder;
import lombok.Getter;

import java.time.Instant;

/**
 * Response DTO for category data.
 *
 * Deliberately excludes:
 *   - user / userId → clients already know who they are (JWT), no need to echo it back.
 *     Also prevents leaking user IDs in responses.
 *   - updatedAt → not needed for the frontend in MVP.
 *
 * Generated by CategoryMapper (MapStruct) — no manual mapping code needed.
 *
 * Used in:
 *   GET  /categories       → List<CategoryResponse>
 *   GET  /categories/{id}  → CategoryResponse
 *   POST /categories       → CategoryResponse
 *   PUT  /categories/{id}  → CategoryResponse
 *
 * Also embedded as CategorySummary inside ExpenseResponse and IncomeResponse
 * (but that's a different, flatter shape — see ExpenseResponse.CategorySummary).
 */
@Getter
@Builder
public class CategoryResponse {

    private Long id;
    private String name;
    private CategoryType type;
    private String color;
    private String icon;
    private Instant createdAt;
}
